baseURL: http://www.starlakecs.com
languageCode: en-us
title: Starlake Consulting Services
theme: hugo-fresh
publishdir: "./starlakecs.github.io"

googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description: Starlake Consulting Services.
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/fresh.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Delivering value through innovations
    # Hero subtitle (optional)
    subtitle: Your one stop solution for complete product development and life cycle management.
    # Button text
    buttontext: About Us
    # Where the main hero button links to
    buttonlink: /agb
    # Hero image (from static/images/___)
    image: illustrations/11376173_4731142.jpg
    # Footer logos (from static/images/logos/clients/___.svg)
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Industry
    sublinks:
    - title: Industrial Automation
      url: /
    - title: Health Care
      url: /
    - title: Cyber Security
      url: /blog/cybersecurity
    - title: SME
      url: /
  - title: Products
    sublinks:
    - title: Kiosk
      url: /blog/first
    - title: Robotic Arm Controllers
      url: /
    - title: HMI
      url: /
  section1:
    title: Our expertise
    tiles:
    - title: Mobile App Development
      icon: mouse-globe
      text: Android and iOS mobile application development.
      url: /
      buttonText: Get started
    - title: Cloud integration for SME
      icon: laptop-cloud
      text: Cloud based IT support for small and medium scale industries.
      url: /
      buttonText: Get started
    - title: Product Development
      icon: plug-cloud
      text: Design and development of connected devices.
      url: /
      buttonText: Get started
  section2:
    title: Industry 
    features:
    - title: Health Care
      text: We have expertise in bio medical device development using bare metal and RTOS based architecture. 
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Industry 4.0
      text: With secure connectivity as backbone for industrial automation. We provide expertise in end to end product development and lifecycle support.
      icon: doc-sync
    - title: Secure Systems
      text: Always connected devices provide security threats. We have expertise in development of secure products.
      icon: mobile-feed
  section5: false
  footer:
    # Logo (from /images/logos/___)
    logo: fresh.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/starlakecs
      # Icons are from Font Awesome
      icon: github
    - link: https://github.com/Starlakecs
      icon: dribbble
    - link: https://facebook.com/starlakecs
      icon: facebook
    - link: https://twitter.com/starlakecs
      icon: twitter
    bulmalogo: false
    quicklinks:
      column1:
        title: "Products"
        links:
        - text: Secure Systems
          link: /
        - text: Access Control
          link: /
        - text: Kiosk
          link: /
        - text: IoT
          link: /
        - text: SME IT
          link: /agb
      column2:
        title: "Industry"
        links:
        - text: Health Care
          link: /
        - text: Automation
          link: /
        - text: Cyber Security
          link: /
        - text: Mobile
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second
